-- MySQL Script generated by MySQL Workbench
-- lun. 20 mai 2019 11:13:55 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema data_tube
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `data_tube` ;

-- -----------------------------------------------------
-- Schema data_tube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `data_tube` DEFAULT CHARACTER SET utf8mb4 ;
USE `data_tube` ;

-- -----------------------------------------------------
-- Table `data_tube`.`language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_tube`.`language` ;

CREATE TABLE IF NOT EXISTS `data_tube`.`language` (
  `id` VARCHAR(16) NOT NULL,
  `code` VARCHAR(16) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `data_tube`.`videoCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_tube`.`videoCategory` ;

CREATE TABLE IF NOT EXISTS `data_tube`.`videoCategory` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `data_tube`.`channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_tube`.`channel` ;

CREATE TABLE IF NOT EXISTS `data_tube`.`channel` (
  `id` VARCHAR(64) NOT NULL,
  `title` VARCHAR(1000) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `publishedAt` VARCHAR(45) NOT NULL,
  `subscriberCount` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `data_tube`.`video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_tube`.`video` ;

CREATE TABLE IF NOT EXISTS `data_tube`.`video` (
  `id` VARCHAR(64) NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `description` VARCHAR(3000) NOT NULL,
  `publishedAt` DATETIME NOT NULL,
  `duration` INT NOT NULL,
  `viewCount` INT NOT NULL,
  `likeCount` INT NULL,
  `dislikeCount` INT NULL,
  `commentCount` INT NULL,
  `definition` VARCHAR(2) NOT NULL,
  `hasCaption` TINYINT(1) NOT NULL,
  `isLicensed` TINYINT(1) NOT NULL,
  `languageId` VARCHAR(16) NULL,
  `videoCategoryId` INT NULL,
  `channelId` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fkVideoLanguage1Idx` (`languageId` ASC),
  INDEX `fkVideoVideoCategory1Idx` (`videoCategoryId` ASC),
  INDEX `fkVideoChannel1Idx` (`channelId` ASC),
  CONSTRAINT `fkVideoLanguage1`
    FOREIGN KEY (`languageId`)
    REFERENCES `data_tube`.`language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkVideoVideoCategory1`
    FOREIGN KEY (`videoCategoryId`)
    REFERENCES `data_tube`.`videoCategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkVideoChannel1`
    FOREIGN KEY (`channelId`)
    REFERENCES `data_tube`.`channel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `data_tube`.`playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_tube`.`playlist` ;

CREATE TABLE IF NOT EXISTS `data_tube`.`playlist` (
  `id` VARCHAR(64) NOT NULL,
  `publishedAt` DATETIME NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  `description` VARCHAR(3000) NULL,
  `channelId` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fkPlaylistChannel1Idx` (`channelId` ASC),
  CONSTRAINT `fkPlaylistChannel1`
    FOREIGN KEY (`channelId`)
    REFERENCES `data_tube`.`channel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `data_tube`.`thumbnail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_tube`.`thumbnail` ;

CREATE TABLE IF NOT EXISTS `data_tube`.`thumbnail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(64) NOT NULL,
  `size` VARCHAR(16) NOT NULL,
  `width` INT NOT NULL,
  `height` INT NOT NULL,
  `channelId` VARCHAR(64) NULL,
  `playlistId` VARCHAR(64) NULL,
  `videoId` VARCHAR(64) NULL,
  PRIMARY KEY (`id`),
  INDEX `fkThumbnailChannel1Idx` (`channelId` ASC),
  INDEX `fkThumbnailPlaylist1Idx` (`playlistId` ASC),
  INDEX `fkThumbnailVideo1Idx` (`videoId` ASC),
  CONSTRAINT `fkThumbnailChannel1`
    FOREIGN KEY (`channelId`)
    REFERENCES `data_tube`.`channel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkThumbnailPlaylist1`
    FOREIGN KEY (`playlistId`)
    REFERENCES `data_tube`.`playlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkThumbnailVideo1`
    FOREIGN KEY (`videoId`)
    REFERENCES `data_tube`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `data_tube`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_tube`.`tag` ;

CREATE TABLE IF NOT EXISTS `data_tube`.`tag` (
  `id` INT NOT NULL,
  `value` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `data_tube`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_tube`.`comment` ;

CREATE TABLE IF NOT EXISTS `data_tube`.`comment` (
  `id` VARCHAR(128) NOT NULL,
  `publishedAt` DATETIME NOT NULL,
  `videoId` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fkCommentVideo1Idx` (`videoId` ASC),
  CONSTRAINT `fkCommentVideo1`
    FOREIGN KEY (`videoId`)
    REFERENCES `data_tube`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `data_tube`.`videoHasTag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_tube`.`videoHasTag` ;

CREATE TABLE IF NOT EXISTS `data_tube`.`videoHasTag` (
  `videoId` VARCHAR(64) NOT NULL,
  `tagId` INT NOT NULL,
  INDEX `fkVideoHasTagTag1Idx` (`tagId` ASC),
  INDEX `fkVideoHasTagVideo1Idx` (`videoId` ASC),
  CONSTRAINT `fkVideoHasTagVideo1`
    FOREIGN KEY (`videoId`)
    REFERENCES `data_tube`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkVideoHasTagTag1`
    FOREIGN KEY (`tagId`)
    REFERENCES `data_tube`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `data_tube`.`playlistHasVideo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_tube`.`playlistHasVideo` ;

CREATE TABLE IF NOT EXISTS `data_tube`.`playlistHasVideo` (
  `playlistId` VARCHAR(64) NOT NULL,
  `videoId` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`playlistId`, `videoId`),
  INDEX `fkPlaylistHasVideoVideo1Idx` (`videoId` ASC),
  INDEX `fkPlaylistHasVideoPlaylist1Idx` (`playlistId` ASC),
  CONSTRAINT `fkPlaylistHasVideoPlaylist1`
    FOREIGN KEY (`playlistId`)
    REFERENCES `data_tube`.`playlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkPlaylistHasVideoVideo1`
    FOREIGN KEY (`videoId`)
    REFERENCES `data_tube`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `data_tube`.`region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_tube`.`region` ;

CREATE TABLE IF NOT EXISTS `data_tube`.`region` (
  `id` VARCHAR(2) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `data_tube`.`videoCategoryHasRegion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_tube`.`videoCategoryHasRegion` ;

CREATE TABLE IF NOT EXISTS `data_tube`.`videoCategoryHasRegion` (
  `videoCategoryId` INT NOT NULL,
  `regionId` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`videoCategoryId`, `regionId`),
  INDEX `fkVideoCategoryHasRegionRegion1Idx` (`regionId` ASC),
  INDEX `fkVideoCategoryHasRegionVideoCategory1Idx` (`videoCategoryId` ASC),
  CONSTRAINT `fkVideoCategoryHasRegionVideoCategory1`
    FOREIGN KEY (`videoCategoryId`)
    REFERENCES `data_tube`.`videoCategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkVideoCategoryHasRegionRegion1`
    FOREIGN KEY (`regionId`)
    REFERENCES `data_tube`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `data_tube`.`videoIsPopularInRegion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_tube`.`videoIsPopularInRegion` ;

CREATE TABLE IF NOT EXISTS `data_tube`.`videoIsPopularInRegion` (
  `videoId` VARCHAR(64) NOT NULL,
  `regionId` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`videoId`, `regionId`),
  INDEX `fkVideoHasRegionRegion1Idx` (`regionId` ASC),
  INDEX `fkVideoHasRegionVideo1Idx` (`videoId` ASC),
  CONSTRAINT `fkVideoHasRegionVideo1`
    FOREIGN KEY (`videoId`)
    REFERENCES `data_tube`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkVideoHasRegionRegion1`
    FOREIGN KEY (`regionId`)
    REFERENCES `data_tube`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `data_tube`.`video_is_popular_in_region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_tube`.`video_is_popular_in_region` ;

CREATE TABLE IF NOT EXISTS `data_tube`.`video_is_popular_in_region` (
  `video_id` VARCHAR(64) NOT NULL,
  `region_id` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`video_id`, `region_id`),
  INDEX `fk_video_has_region_region1_idx` (`region_id` ASC),
  INDEX `fk_video_has_region_video1_idx` (`video_id` ASC),
  CONSTRAINT `fk_video_has_region_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `data_tube`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_has_region_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `data_tube`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
